### ISSUE TITLE
GVProf shows nothing after execution

### ISSUE THREAD

**Issue by WilliamWangPeng** [GVProf/GVProf#30]
Hi dear authors,  
    I'm using GVProf nowadays, but after executing  $gvprof -e redundancy ./vectorAdd, it shows these messages, but no profiling information. Where is the profiling information?  

![image](https://user-images.githubusercontent.com/51076736/127336495-25d671e5-e098-4844-82ba-a17cf31a0733.png)

thank you  
best regards  
William

**Comment by Jokeren** [comment]
What GPU are you using?

Can you try another mode? `gvprof -e data_flow ./vectorAdd`

**Comment by Jokeren** [comment]
Also, `gvprof -v` will be helpful. You can paste `gvprof.log` here.

**Comment by WilliamWangPeng** [comment]
> What GPUs are you using? What's the CUDA version?
> 
> Can you try another mode? `gvprof -e data_flow ./vectorAdd`
![image](https://user-images.githubusercontent.com/51076736/127465088-6547adc6-5185-4358-9207-dd33e372f4d2.png)

hi dear @Jokeren   
thank you for your help 🥇   
here is the info of my GPU, and I have also tried `gvprof -e data_flow ./vectorAdd` as shown above,   
![image](https://user-images.githubusercontent.com/51076736/127466091-4fd27a1d-0ee4-496b-be44-a13d267018e0.png)

 
I have also tried `gvprof -v`, but there  is "Empty event", and there is no gvprof.log in the fold.    

thank you again
best regards 
William

**Comment by Jokeren** [comment]
I actually meant `gvprof -v -e data_flow ./vectorAdd`. Then you should see a gvprof.log file.

The GPU runtime seems fine on your machine.

**Comment by WilliamWangPeng** [comment]
> I actually meant `gvprof -v -e data_flow ./vectorAdd`. Then you should see a gvprof.log file.
> 
> The GPU runtime seems fine on your machine.
Hi dear @Jokeren   I used the **gvprof -v -e data_flow ./vectorAdd** command, and the result is as following.   
![image](https://user-images.githubusercontent.com/51076736/128676465-f46f41a1-aad0-4243-b0f7-62a10493b3d6.png)

but I still can not get the data_flow performance of the vectorAdd example.    

thank you  
best regards 
William

**Comment by Jokeren** [comment]
@WilliamWangPeng It means hpcrun is not on the path.

    # Setup environment variables
    export PATH=$(pwd)/gvprof/bin:$PATH
    export PATH=$(pwd)/gvprof/hpctoolkit/bin:$PATH
    export PATH=$(pwd)/gvprof/redshow/bin:$PATH

**Comment by WilliamWangPeng** [comment]
> @WilliamWangPeng It means hpcrun is not on the path.
> 
> ```
> # Setup environment variables
> export PATH=$(pwd)/gvprof/bin:$PATH
> export PATH=$(pwd)/gvprof/hpctoolkit/bin:$PATH
> export PATH=$(pwd)/gvprof/redshow/bin:$PATH
> ```

Hi dear @Jokeren   
    I have already built the path at ~/.bashrc at the very beginning of build GVProf.  :-)  

![image](https://user-images.githubusercontent.com/51076736/129125033-be584c07-fcbc-4219-b2e9-84b505171ecf.png)

**Comment by Jokeren** [comment]
Got you, but the symptom indicates hpcrun cannot be found. I wonder if you really have hpcrun under `/home/wangpeng/tools/GPU/GVProf/gvprof/hpctoolkit/bin` or not. Can you use `ls /home/wangpeng/tools/GPU/GVProf/gvprof/hpctoolkit/bin` ?

**Comment by WilliamWangPeng** [comment]
> Got you, but the symptom indicates hpcrun cannot be found. I wonder if you really have hpcrun under `/home/wangpeng/tools/GPU/GVProf/gvprof/hpctoolkit/bin` or not. Can you use `ls /home/wangpeng/tools/GPU/GVProf/gvprof/hpctoolkit/bin` ?

oh dear @Jokeren   
    You are really a genius，:-） I do not have hpcrun, I will try to install it tomorrow after the meeting with a technology company. 

![image](https://user-images.githubusercontent.com/51076736/129147875-c80725c0-d163-4234-8e51-1faac4769aeb.png)

**Comment by Jokeren** [comment]
If hpctoolkit is installed, you should be able to find a `hpctoolkit` directory under `/home/wangpeng/tools/GPU/GVProf/gvprof`. Since you didn't see it, probably the install script failed when installing hpctoolkit.

Let me know if you need any help install hpctoolkit. I'll have some time next week. Feel free to shoot me an email to schedule a meeting.
