### ISSUE TITLE
[MemoryProfiler] unordered map bug

### ISSUE THREAD

**Issue by Jokeren** [GVProf/GVProf#31]
include/analysis/memory_profile.h:118:6: error: ‘unordered_map’ in namespace ‘std’ does not name a template type
 std::unordered_map<u64, u64> _addresses_map;
      ^~~~~~~~~~~~~
include/analysis/memory_profile.h:118:1: note: ‘std::unordered_map’ is defined in header ‘<unordered_map>’; did you forget to ‘#include <unordered_map>’?
include/analysis/memory_profile.h:1:1:

@Lin-Mao

**Comment by Lin-Mao** [comment]
I didn't. I fixed it now.

**Comment by Lin-Mao** [comment]
The bug didn't appear in my compilation.

**Comment by Lin-Mao** [comment]
It's strange. I removed it and compiled it again. It also works well.

**Comment by Jokeren** [comment]
The header file of `unordered_map` might be in your system's default include path. Please point your commit here and close the issue.

**Comment by Lin-Mao** [comment]
OK, got it. Thanks!

**Comment by Lin-Mao** [comment]
Fixed it. @https://github.com/GVProf/redshow/commit/f8f3b59d0be12988a3f2ea09414ab133b299dba1
